#!/usr/bin/env bash

###############################################################################
# cgrates-reload
#
# Author: IvozProvider <vozip+ivozprovider@irontec.com>
# Date: 2019/04/04
#
###############################################################################
#
# Reload Cgrates helper script
#
###############################################################################

FLUSHALL=1

# Remove every redis key except accounts info and tp_versions
if [ $FLUSHALL -eq 1 ]; then
    RELOADDESTINATIONS=1 # -F forces -D
    SENTINEL_MASTER=`redis-cli -h data.ivozprovider.local -p 26379 sentinel get-master-addr-by-name mymaster | head -n 1`
    echo -e "\e[1;32m* \e[1;97mDetected Redis Sentinel Master: $SENTINEL_MASTER\n\e[0m"
    echo -e "\e[1;31mThis operation cannot be undone, proceed?\n\e[0m"
    read -p "Press enter to continue"

#    echo -e "\e[1;32m* \e[1;31mFlushing every key except 'acc_*' and 'tp_versions' ...\e[0m"
#    redis-cli -h $SENTINEL_MASTER -n 10 keys \* | egrep -v "^acc_" | egrep -v "^tp_versions" | xargs redis-cli -h $SENTINEL_MASTER -n 10 del
    echo -e "\e[1;32m* \e[1;31mFlushing every key except 'tp_versions' ...\e[0m"
    redis-cli -h $SENTINEL_MASTER -n 10 keys \* | egrep -v "^tp_versions" | xargs redis-cli -h $SENTINEL_MASTER -n 10 del
    exit
fi

